#DATABASE CONFIGURATIONS
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/annalis
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    generate-ddl: true

app-properties:
  api-username: admin
  api-password: admin

proc:
  scheduler: 86400

twilio:
  account_sid: AC5b274f17de1cfcf105463db66480bb73
  auth_token: d83a82722409c5cde77c37860bb9863b
  trial_number: +19124058761

#LOGGING CONFIGURATION
logging:
  config: classpath:logback.xml

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER