
#DATABASE CONFIGURATIONS
spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${JDBC_URL:jdbc:mysql://localhost:3306/annalis}
#    username: ${DATABASE_USERNAME:root}
#    password: ${DATABASE_PASSWORD:root}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        show_sql: true
#        format_sql: true
#    generate-ddl: true

  datasource:
    url: ${JDBC_URL:jdbc:h2:mem:mydb}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:password}
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

app-properties:
  api-username: ${API_USERNAME:admin}
  api-password: ${API_PASSWORD:admin}

proc:
  scheduler: ${PROC_SCHEDULER:86400}

twilio:
  account_sid: ${TWILIO_ACCOUNT_SID:AC5b274f17de1cfcf105463db66480bb73}
  auth_token: ${TWILIO_AUTH_TOKEN:d83a82722409c5cde77c37860bb9863b}
  trial_number: ${TWILIO_TRIAL_NUMBER:+19124058761}