apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: lendtech-repayment-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lendtech-repayment-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization