kind: Secret
apiVersion: v1
metadata:
  name: lendtech-repayment-api
data:
  jdbc.username: bG95YWx0eWluaG91c2U=
  jdbc.password: TE95YWx0eSEhMzIxVGVzdA==
  api.username: YWRtaW4=
  api.password: YWRtaW4=
type: Opaque