#publish your docker image to github container registry
name: publish
on: [push]
jobs:
  build-and-containerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: Annaliskirwa
          password: ${{ secrets.LENDTECH_GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Debug maven and java
        run: |
          java -version && mvn -v >> debug.txt
          cat debug.txt
      - name: Build with Maven
        run: |
          mvn package
      - name: Build, tag and push Docker image
        run: |
          docker build . --tag ghcr.io/annaliskirwa/lendtech-repayment-api:latest
          docker push ghcr.io/annaliskirwa/lendtech-repayment-api:latest
  deploy:
    needs: build-and-containerize
    runs-on: ubuntu-latest
    steps:
      - name: Debug deployment files
        run: |
          echo ls-la
      - name: Connect with openshift
        run: |
          oc login --token=sha256~0Mu_dP7ESDP2cmkckrKpjH9pC2hog97Ri3SZar1PqgA --server=https://api.sandbox-m3.1530.p1.openshiftapps.com:6443
      - name: Select openshift project
        run: |
          oc project annaliskirwa-dev
      - name: Delete deployment
        run: |
          oc delete deployment lendtech-repayment-api
      - name: Deploy deployment files
        run: |
          oc apply -f ${GITHUB_WORKSPACE}/ocp -n annaliskirwa-dev