#publish your docker image to github container registry
name: publish
on: [push]
jobs:
  build-and-containerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: Annaliskirwa
          password: ${{ secrets.LENDTECH_GITHUB_TOKEN }}
      - name: Maven
        run: |
          mvn package
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag kirwa9431/lendtech-repayment-api:latest
          docker push kirwa9431/lendtech-repayment-api:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect with openshift
        run: |
          oc login --token=sha256~TgrMefu3Fgd7kR9MuQUdnfqlteAcg4jLBbJVxERJOPE --server=https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
      - name: Select openshift project
        run: |
          oc project annaliskirwa-dev
      - name: Delete deployment
        run: |
          oc delete deployment container-registry-example
      - name: Deploy deployment files
        run: |
          oc apply -f ${GITHUB_WORKSPACE}/ocp -n annaliskirwa-dev