#publish your docker image to github container registry
name: publish
on: [push]
jobs:
  get-random-image-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate random image tag variable
        run: |
          export IMAGE_TAG=$((RANDOM))
          echo "The random tag is $IMAGE_TAG"
          echo "::set-output name=imageTag::$IMAGE_TAG"
  build-and-containerize:
    needs: get-random-image-tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: Annaliskirwa
          password: ${{ secrets.LENDTECH_GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Debug maven and java
        run: |
          java -version && mvn -v >> debug.txt
          cat debug.txt
      - name: Build with Maven
        run: |
          mvn package
      - name: Build, tag and push Docker image
        run: |
          imagetag=${{ needs.get-random-image-tag.outputs.imageTag }}
          echo $imagetag
          docker build . --tag ghcr.io/annaliskirwa/lendtech-repayment-api:$imagetag
          docker push ghcr.io/annaliskirwa/lendtech-repayment-api:$imagetag
  deploy-ocp-manifests:
    needs: build-and-containerize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debug deployment files and change pwd
        run: |
          cd ..
          pwd
          ls
      - name: Connect with openshift
        run: |
          oc login --token=sha256~${{ secrets.LENDTECH_OCP_TOKEN }} --server=https://api.sandbox-m3.1530.p1.openshiftapps.com:6443
      - name: Select openshift project
        run: |
          oc project annaliskirwa-dev
#      - name: Delete deployment
#        run: |
#          oc delete deployment lendtech-repayment-api
#      - name: Deploy deployment files
#        run: |
#          oc apply -f ${GITHUB_WORKSPACE}/ocp -n annaliskirwa-dev
      - name: Deploy deployment files
        run: |
          oc apply -f ${{ github.workspace }}/ocp -n annaliskirwa-dev